services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  node:
    image: node:latest
    container_name: node-app
    working_dir: /app
    command: bash -c "npm install && npx tsup src --out-dir build && node build/server.js"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DB}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongo-data: